#### Geomtery of 3D Affine Transformation
##### Objective:
Obserserve the geometrical interpretation of the 3D transformation

Similar to 2D affine transformation, we'll use a 3D house to understand what occurs when we apply the matrix transformation.

#### Translation
$$\begin{pmatrix} x' \\ y' \\ z' \\ 1 \end{pmatrix} = \begin{pmatrix} x +t_x \\ y + t_y \\ z + t_z \\ 1 \end{pmatrix} = \begin{pmatrix} 
1 & 0 & 0 & t_x \\
0 & 1 & 0 & t_y \\
0 & 0 & 1 & t_z \\
0 & 0 & 0 & 1
\end{pmatrix} \begin{pmatrix} x \\ y \\ z \\ 1 \end{pmatrix}$$

<img src="image_U7/original_A1.png" height="300" width="300"/>
<img src="image_U7/translated_A1.png" height="300" width="300"/>
<img src="image_U7/translated_A2.png" height="300" width="300"/>


##### The inverse  
$$
\begin{pmatrix} 
1 & 0 & 0 & -t_x \\
0 & 1 & 0 & -t_y \\
0 & 0 & 1 & -t_z \\
0 & 0 & 0 & 1
\end{pmatrix} = \begin{pmatrix} 
1 & 0 & 0 & t_x \\
0 & 1 & 0 & t_y \\
0 & 0 & 1 & t_z \\
0 & 0 & 0 & 1
\end{pmatrix}^{-1}
$$

**Example:** if we apple the following transformation: 
$$\begin{pmatrix} 
1 & 0 & 0 & 4 \\
0 & 1 & 0 & 4 \\
0 & 0 & 1 & 4 \\
0 & 0 & 0 & 1
\end{pmatrix}$$




#### Sclaing

$$\begin{pmatrix} x' \\ y' \\ z' \\ 1 \end{pmatrix} = \begin{pmatrix} S_xx\\ S_yy \\ S_zz \\ 1 \end{pmatrix} = \begin{pmatrix} 
S_x & 0 & 0 & 0 \\
0 & S_y & 0 & 0 \\
0 & 0 & S_z & 0 \\
0 & 0 & 0 & 1
\end{pmatrix} \begin{pmatrix} x \\ y \\ z \\ 1 \end{pmatrix}$$

**Example:** Uniform Scaling by Factor of 3:

<img src="image_U7/Scale_Uniform.png" height="300" width="300"/>

**Example:** Non-Uniform Scaling:  

<img src="image_U7/Scale_NU1.png" height="300" width="300"/>
<img src="image_U7/Scale_NU2.png" height="300" width="300"/>
<img src="image_U7/Scale_NU3.png" height="300" width="300"/>

##### Non-Uniform Scaling special case:
If we use a scaling factor of -1 for one of the coordinates, this coordinate being flipped leads to a reflection of the **space** about the plane created by the two other coordinates.

$$\begin{pmatrix} 
-1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Reflec_YZ.png" height="400" width="400"/>

$$\begin{pmatrix} 
1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Relfec_XZ.png" height="400" width="400"/>

$$\begin{pmatrix} 
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Reflec_XY.png" height="400" width="400"/>

##### The Inverse
$$\begin{pmatrix} 
\frac{1}{S_x} & 0 & 0 & 0 \\
0 & \frac{1}{S_y}  & 0 & 0 \\
0 & 0 & \frac{1}{S_z}  & 0 \\
0 & 0 & 0 & 1
\end{pmatrix} = \begin{pmatrix} 
S_x & 0 & 0 & 0 \\
0 & S_y & 0 & 0 \\
0 & 0 & S_z & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}^{-1}$$

**Tip** "Mirror Plane" will always be the two axis (Rows in the matrix) that haven't be negated.

#### Shearing
$$\begin{pmatrix} x' \\ y' \\ z' \\ 1 \end{pmatrix} = \begin{pmatrix} x + s_{xy}y + s_{xz}z \\ s_{yz}x + y + s_{yz}z \\ s_{zx}z + s_{zy}y + z \\ 1 \end{pmatrix} + \begin{pmatrix} 
1 & s_{xy} & s_{xz} & 0 \\
s_{yx} & 1 & s_{yz} & 0 \\
s_{zx} & s_{zy} & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix} \begin{pmatrix} x \\ y \\ z \\ 1 \end{pmatrix}$$

**Example**  

<img src="image_U7/Original_A2.png" height="400" width="400"/>
<img src="image_U7/Shear_A1.png" height="400" width="400"/>

#### Rotation
In 2D we only needed a point of rotation, in 3D we need an **axis** of rotation.

<img src="image_U7/RotAxis.png" height="400" width="400"/>

$$\begin{pmatrix} x' \\ y' \\ z' \end{pmatrix} = \mathbf{R_i}(\alpha) \begin{pmatrix} x \\ y \\ z \end{pmatrix}$$

##### X-Axis:
$$\mathbf{R_x}(\theta) = \begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & \cos\theta & -\sin\theta & 0 \\
0 & \sin\theta & \cos\theta & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Rotate_XA1.png" height="400" width="400"/>

##### Y-Axis:
$$\mathbf{R_y}(\phi) = \begin{pmatrix}
\cos\phi & 0 & \sin\phi & 0 \\
0 & 1 & 0 & 0 \\
-\sin\phi & 0 & \cos\phi & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Rotate_Y.png" height="400" width="400"/>

##### Z-Axis:
$$\mathbf{R_z}(\psi) = \begin{pmatrix}
\cos\psi & -\sin\psi & 0 & 0 \\
\sin\psi & \cos\psi & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

<img src="image_U7/Rotate_z.png" height="400" width="400"/>

Notice that the rotation about the axis in discussion has it's respective row as the unit vector since its not changed.

##### The Inverse:
The matrix of the inverse transformation is the inverse of the original transformation
##### X-Axis:
$$\mathbf{R_x}(\theta) = \begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & \cos-\theta & -\sin-\theta & 0 \\
0 & \sin-\theta & \cos-\theta & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

##### Y-Axis:
$$\mathbf{R_y}(\phi) = \begin{pmatrix}
\cos-\phi & 0 & \sin-\phi & 0 \\
0 & 1 & 0 & 0 \\
-\sin-\phi & 0 & \cos-\phi & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$

##### Z-Axis:
$$\mathbf{R_z}(\psi) = \begin{pmatrix}
\cos-\psi & -\sin-\psi & 0 & 0 \\
\sin-\psi & \cos-\psi & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}$$


In [16]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def compute_rotation(a, b, c):
    # X rotation
    Rx = np.array([
        [1, 0, 0, 0],
        [0, np.cos(a), -np.sin(a), 0],
        [0, np.sin(a), np.cos(a), 0],
        [0, 0, 0, 1]
    ])
    
    # Y rotation
    Ry = np.array([
        [np.cos(b), 0, np.sin(b), 0],
        [0, 1, 0, 0],
        [-np.sin(b), 0, np.cos(b), 0],
        [0, 0, 0, 1]
    ])
    
    # Z rotation
    Rz = np.array([
        [np.cos(c), -np.sin(c), 0, 0],
        [np.sin(c), np.cos(c), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
    
    return Rx @ Ry @ Rz

print(compute_rotation(np.pi/4, np.pi/2, np.pi/3))
print(compute_rotation(0, np.pi/2, 7*np.pi/12))

[[ 3.06161700e-17 -5.30287619e-17  1.00000000e+00  0.00000000e+00]
 [ 9.65925826e-01 -2.58819045e-01 -4.32978028e-17  0.00000000e+00]
 [ 2.58819045e-01  9.65925826e-01  4.32978028e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-1.58480958e-17 -5.91458986e-17  1.00000000e+00  0.00000000e+00]
 [ 9.65925826e-01 -2.58819045e-01  0.00000000e+00  0.00000000e+00]
 [ 2.58819045e-01  9.65925826e-01  6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
